version: '3.7'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment:
      discovery.type: single-node
    restart: "no"
    ports:
      - '9200:9200'
      - '9300:9300'
    expose:
      - '9200'
      - '9300'
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    ports:
      - "5601:5601"
    expose:
      - "5601"
    depends_on:
      - elasticsearch

networks:
  default: