
#spring:
#  cloud:
#    stream:
#      default-binder: kafka
#      kafka:
#        binder:
#          brokers:
#            - localhost:9092
#      bindings:
#        input:
#          binder: kafka
#          destination: dbserver1.public.member
#          content-type: application/json
#          group: input-group-1

server:
  port: 8082
